<?php

namespace Database\Seeders;

use App\Models\Institution;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class InstitutionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $institutions = [
            // Public Universities
            [
                'name' => 'University of Ghana',
                'email' => 'info@ug.edu.gh',
                'phone' => '+233 302 213820',
                'address' => 'Legon',
                'city' => 'Accra',
                'state' => 'Greater Accra',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.ug.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Kwame Nkrumah University of Science and Technology',
                'email' => 'info@knust.edu.gh',
                'phone' => '+233 3220 20021',
                'address' => 'Kumasi',
                'city' => 'Kumasi',
                'state' => 'Ashanti',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.knust.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'University of Cape Coast',
                'email' => 'info@ucc.edu.gh',
                'phone' => '+233 3321 32480',
                'address' => 'Cape Coast',
                'city' => 'Cape Coast',
                'state' => 'Central',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.ucc.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'University of Education, Winneba',
                'email' => 'info@uew.edu.gh',
                'phone' => '+233 2333 220465',
                'address' => 'Winneba',
                'city' => 'Winneba',
                'state' => 'Central',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.uew.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'University for Development Studies',
                'email' => 'info@uds.edu.gh',
                'phone' => '+233 3720 22025',
                'address' => 'Tamale',
                'city' => 'Tamale',
                'state' => 'Northern',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.uds.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'University of Mines and Technology',
                'email' => 'info@umat.edu.gh',
                'phone' => '+233 3120 20324',
                'address' => 'Tarkwa',
                'city' => 'Tarkwa',
                'state' => 'Western',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.umat.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'University of Health and Allied Sciences',
                'email' => 'info@uhas.edu.gh',
                'phone' => '+233 3621 96000',
                'address' => 'Ho',
                'city' => 'Ho',
                'state' => 'Volta',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.uhas.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'University of Energy and Natural Resources',
                'email' => 'info@uenr.edu.gh',
                'phone' => '+233 3522 02022',
                'address' => 'Sunyani',
                'city' => 'Sunyani',
                'state' => 'Bono',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.uenr.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Ghana Institute of Management and Public Administration',
                'email' => 'info@gimpa.edu.gh',
                'phone' => '+233 302 401681',
                'address' => 'Achimota',
                'city' => 'Accra',
                'state' => 'Greater Accra',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.gimpa.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Ghana Communication Technology University',
                'email' => 'info@gctu.edu.gh',
                'phone' => '+233 302 406000',
                'address' => 'Tesano',
                'city' => 'Accra',
                'state' => 'Greater Accra',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.gctu.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            // Technical Universities
            [
                'name' => 'Accra Technical University',
                'email' => 'info@atu.edu.gh',
                'phone' => '+233 302 248471',
                'address' => 'Accra',
                'city' => 'Accra',
                'state' => 'Greater Accra',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.atu.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Kumasi Technical University',
                'email' => 'info@ktu.edu.gh',
                'phone' => '+233 3220 20021',
                'address' => 'Kumasi',
                'city' => 'Kumasi',
                'state' => 'Ashanti',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.ktu.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Takoradi Technical University',
                'email' => 'info@ttu.edu.gh',
                'phone' => '+233 3120 20420',
                'address' => 'Takoradi',
                'city' => 'Takoradi',
                'state' => 'Western',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.ttu.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Koforidua Technical University',
                'email' => 'info@ktu.edu.gh',
                'phone' => '+233 3420 20120',
                'address' => 'Koforidua',
                'city' => 'Koforidua',
                'state' => 'Eastern',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.ktu.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Ho Technical University',
                'email' => 'info@htu.edu.gh',
                'phone' => '+233 3620 20120',
                'address' => 'Ho',
                'city' => 'Ho',
                'state' => 'Volta',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.htu.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Sunyani Technical University',
                'email' => 'info@stu.edu.gh',
                'phone' => '+233 3520 20120',
                'address' => 'Sunyani',
                'city' => 'Sunyani',
                'state' => 'Bono',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.stu.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Tamale Technical University',
                'email' => 'info@tatu.edu.gh',
                'phone' => '+233 3720 20120',
                'address' => 'Tamale',
                'city' => 'Tamale',
                'state' => 'Northern',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.tatu.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Cape Coast Technical University',
                'email' => 'info@cctu.edu.gh',
                'phone' => '+233 3321 32480',
                'address' => 'Cape Coast',
                'city' => 'Cape Coast',
                'state' => 'Central',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.cctu.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            // Major Private Universities
            [
                'name' => 'Ashesi University',
                'email' => 'info@ashesi.edu.gh',
                'phone' => '+233 302 610330',
                'address' => 'Berekuso',
                'city' => 'Accra',
                'state' => 'Greater Accra',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.ashesi.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Central University',
                'email' => 'info@central.edu.gh',
                'phone' => '+233 302 313185',
                'address' => 'Miotso',
                'city' => 'Accra',
                'state' => 'Greater Accra',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.central.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Valley View University',
                'email' => 'info@vvu.edu.gh',
                'phone' => '+233 302 200611',
                'address' => 'Techiman',
                'city' => 'Techiman',
                'state' => 'Bono East',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.vvu.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Presbyterian University College',
                'email' => 'info@presbyuniversity.edu.gh',
                'phone' => '+233 302 200611',
                'address' => 'Abetifi',
                'city' => 'Abetifi',
                'state' => 'Eastern',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.presbyuniversity.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Regent University College of Science and Technology',
                'email' => 'info@regent.edu.gh',
                'phone' => '+233 302 542188',
                'address' => 'Accra',
                'city' => 'Accra',
                'state' => 'Greater Accra',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.regent.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Ghana Technology University College',
                'email' => 'info@gtuc.edu.gh',
                'phone' => '+233 302 200611',
                'address' => 'Tesano',
                'city' => 'Accra',
                'state' => 'Greater Accra',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.gtuc.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Wisconsin International University College',
                'email' => 'info@wiuc-ghana.edu.gh',
                'phone' => '+233 302 313185',
                'address' => 'Accra',
                'city' => 'Accra',
                'state' => 'Greater Accra',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.wiuc-ghana.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Methodist University College Ghana',
                'email' => 'info@mucg.edu.gh',
                'phone' => '+233 302 200611',
                'address' => 'Dansoman',
                'city' => 'Accra',
                'state' => 'Greater Accra',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.mucg.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Pentecost University College',
                'email' => 'info@pentvars.edu.gh',
                'phone' => '+233 302 200611',
                'address' => 'Sowutuom',
                'city' => 'Accra',
                'state' => 'Greater Accra',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.pentvars.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Anglican University College of Technology',
                'email' => 'info@anglicanuniversity.edu.gh',
                'phone' => '+233 302 200611',
                'address' => 'Nkoranza',
                'city' => 'Nkoranza',
                'state' => 'Bono East',
                'zip' => null,
                'country' => 'Ghana',
                'website' => 'https://www.anglicanuniversity.edu.gh',
                'logo' => null,
                'is_active' => true,
            ],
        ];

        try {
            DB::transaction(function () use ($institutions) {
                foreach ($institutions as $institution) {
                    Institution::create($institution);
                }
            });
        } catch (\Exception $e) {
            Log::error('Failed to seed institutions: '.$e->getMessage());
            throw new \Exception('Failed to seed institutions. Please try again.');
        }
    }
}
